### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Attempt to assign property "icons" on bool in

### ISSUE THREAD

**Issue by arigato-one** [skyverge/woocommerce-shipping-estimate#41]
**What I expected to happen**
I tried to loggin to my admin area, I received this error.
**What happened**
[24-Feb-2022 11:30:48 UTC] PHP Fatal error:  Uncaught Error: Attempt to assign property "icons" on bool in /Applications/MAMP/htdocs/wp-content/plugins/woocommerce-shipping-estimate/lib/skyverge/updater/class-skyverge-plugin-updater.php:631
Stack trace:
#0 /Applications/MAMP/htdocs/wp-content/plugins/woocommerce-shipping-estimate/lib/skyverge/updater/class-skyverge-plugin-updater.php(150): SkyVerge\WooCommerce\PluginUpdater\Updater->set_version_info_cache(false)
#1 /Applications/MAMP/htdocs/wp-includes/class-wp-hook.php(309): SkyVerge\WooCommerce\PluginUpdater\Updater->check_update(Object(stdClass))
#2 /Applications/MAMP/htdocs/wp-includes/plugin.php(189): WP_Hook->apply_filters(Object(stdClass), Array)
#3 /Applications/MAMP/htdocs/wp-includes/option.php(1989): apply_filters('pre_set_site_tr...', Object(stdClass), 'update_plugins')
#4 /Applications/MAMP/htdocs/wp-includes/update.php(357): set_site_transient('update_plugins', Object(stdClass))
#5 /Applications/MAMP/htdocs/wp-includes/update.php(899): wp_update_plugins()
#6 /Applications/MAMP/htdocs/wp-includes/class-wp-hook.php(307): _maybe_update_plugins('')
#7 /Applications/MAMP/htdocs/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#8 /Applications/MAMP/htdocs/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#9 /Applications/MAMP/htdocs/wp-admin/admin.php(175): do_action('admin_init')
#10 /Applications/MAMP/htdocs/wp-admin/index.php(10): require_once('/Applications/M...')
#11 {main}
  thrown in /Applications/MAMP/htdocs/wp-content/plugins/woocommerce-shipping-estimate/lib/skyverge/updater/class-skyverge-plugin-updater.php on line 631

**Steps to reproduce**
Log in into admin area, happened just once, I can't reproduce it anymore.

**Screenshots**
None

**Additional context**
None

**Comment by arigato-one** [comment]
I am back with an update. 
I tried to check for updates, from Admin I pressed the Notification that showed the number of update. It was a different plugin with an update available.
When I pressed, I got the same error as the one from above.

**Comment by jsmusiker** [comment]
@bekarice @maxrice the SkyVerge Account page is down. I believe this is killing customers plugins.php page.

This is down - https://www.skyverge.com/account/
